db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: sisproject
    POSTGRES_DB: sisproject
    POSTGRES_PASSWORD: sisproject
  ports:
    - "5433:5432"

sisproject:
  build: .
  environment:
      DB_HOSTNAME: "db"
      DB_USERNAME: "sisproject"
      DB_PASSWORD: "sisproject"
      DB_PORT: "5432"
      DB_NAME: "sisproject"
      STATIC_ROOT: "/var/www/static/"
  container_name: sisproject
  volumes:
    - ./sisproject:/code/
  hostname: sisproject-app
  command: manage runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  links:
    - db
