# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_method', models.CharField(choices=[('HTTP GET', 'HTTP GET'), ('HTTP POST', 'HTTP POST'), ('FTP', 'FTP'), ('SFTP', 'SFTP'), ('GOOGLE DRIVE', 'GOOGLE DRIVE'), ('S3', 'S3'), ('EMAIL', 'EMAIL')], default='HTTP GET', max_length=30, verbose_name='Description of access protocol')),
                ('availability', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=30, null=True, verbose_name='Last known availability')),
                ('compression', models.CharField(choices=[('DEFLATE', 'DEFLATE'), ('LZ', 'LZ'), ('LZR', 'LZR'), ('LZW', 'LZW')], default=' ', max_length=30, verbose_name='Compression algorithm used with source')),
                ('description', models.TextField(default=' ', verbose_name='Link to digital rights document (e.g. contract)')),
                ('digital_rights', models.URLField(default=' ', max_length=100, verbose_name='Overview of the data source (provided by maintainer)')),
                ('encoding', models.CharField(blank=True, choices=[('US-ASCII', 'US-ASCII'), ('UTF-8', 'UTF-8'), ('UTF-16', 'UTF-16'), ('UTF-32', 'UTF-32')], default='UTF-8', max_length=30, null=True, verbose_name='Character encoding (e.g. UTF-8)')),
                ('encryption', models.CharField(default=' ', max_length=200, verbose_name='Name / link to encryption algorithm used')),
                ('language', models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Portuguese', 'Portuguese'), ('Spanish', 'Spanish')], default='English', max_length=30, null=True, verbose_name='Language in which the data is written')),
                ('last_accessed', models.DateField(auto_now=True, null=True, verbose_name='Last known access')),
                ('last_modified', models.DateField(auto_now_add=True, verbose_name='Last record update')),
                ('last_refreshed', models.DateField(default=' ', verbose_name='Last known refresh date')),
                ('license_type', models.URLField(default=' ', max_length=100, verbose_name='Name of primary business contact')),
                ('maintainer', models.CharField(default=' ', max_length=30, verbose_name='License type (e.g. Open Data Commons)')),
                ('maintainer_email', models.EmailField(default=' ', max_length=255, verbose_name='E-mail address of primary business contact')),
                ('maintainer_phone', models.CharField(default=' ', max_length=255, verbose_name='Phone number of primary business contact')),
                ('pii', models.BooleanField(default=False, verbose_name='TRUE if data source contains personally-identifiable information or protected health information')),
                ('records', models.BigIntegerField(blank=True, default=' ', null=True, verbose_name='Last known record count')),
                ('regex', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='RegEx expression used with access method')),
                ('schema_type', models.CharField(choices=[('None', 'None'), ('Column Headers', 'Column Headers'), ('AVRO', 'AVRO'), ('HXL', 'HXL'), ('JSON-LD', 'JSON-LD'), ('RDF', 'RDF'), ('XML', 'XML')], default=None, max_length=30, verbose_name='Schema type used to describe data source attributes')),
                ('size', models.BigIntegerField(blank=True, default=' ', null=True, verbose_name='Last known size (MB)')),
                ('system_of_record', models.BooleanField(default=False, max_length=30, verbose_name='Last known size (MB)')),
                ('uri_access', models.URLField(default=' ', max_length=100, verbose_name='Access URI for data')),
                ('uri_documenation', models.URLField(blank=True, default=' ', max_length=100, null=True, verbose_name='Link to API documentation')),
                ('uri_endpoint', models.URLField(blank=True, default=' ', max_length=100, null=True, verbose_name='Access URI for endpoint API')),
                ('uri_schema', models.URLField(blank=True, default=' ', max_length=100, null=True, verbose_name='Access URI for schema (supply if schema_type is not "None")')),
                ('title', models.CharField(default=' ', max_length=255, verbose_name='Descriptive title (provided by maintainer)')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visible in view service')),
                ('contact_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sources', related_query_name='source', to='users.Contact')),
                ('tenant_id', models.ManyToManyField(related_query_name='source', to='users.Tenant')),
            ],
        ),
    ]
