# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='encryption',
            field=models.CharField(blank=True, default='UTF-8', max_length=30, null=True, verbose_name='Name / link to encryption algorithm used'),
        ),
        migrations.AlterField(
            model_name='source',
            name='system_of_record',
            field=models.BooleanField(default=False, max_length=30, verbose_name='TRUE if this is a primary resource (i.e. not a replica or extract)'),
        ),
    ]
