# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20160606_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='regex',
            new_name='json_schema',
        ),
    ]
