# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20160606_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='maintainer',
        ),
        migrations.AlterField(
            model_name='source',
            name='contact_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer', to='users.Contact'),
        ),
        migrations.AlterField(
            model_name='source',
            name='license_type',
            field=models.CharField(default=' ', max_length=30, verbose_name='License type (e.g. Open Data Commons)'),
        ),
    ]
