# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sisdatasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_method', models.CharField(choices=[('HTTP GET', 'HTTP GET'), ('HTTP POST', 'HTTP POST'), ('FTP', 'FTP'), ('SFTP', 'SFTP'), ('GOOGLE DRIVE', 'GOOGLE DRIVE'), ('S3', 'S3'), ('EMAIL', 'EMAIL')], default=' ', max_length=30, verbose_name='Description of access protocol')),
                ('availability', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default=' ', max_length=30, null=True, verbose_name='Last known availability')),
                ('compression', models.CharField(choices=[('DEFLATE', 'DEFLATE'), ('LZ', 'LZ'), ('LZR', 'LZR'), ('LZW', 'LZW')], default=' ', max_length=30, verbose_name='Compression algorithm used with source')),
                ('description', models.TextField(default=' ', verbose_name='Link to digital rights document (e.g. contract)')),
                ('digital_rights', models.URLField(default=' ', max_length=100, verbose_name='Overview of the data source (provided by maintainer)')),
                ('encoding', models.CharField(choices=[('UTF-8', 'UTF-8'), ('US-ASCII', 'US-ASCII'), ('UTF-16', 'UTF-16'), ('UTF-32', 'UTF-32')], default=' ', max_length=30, verbose_name='Character encoding (e.g. UTF-8)')),
                ('encryption', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Name / link to encryption algorithm used')),
                ('language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('French', 'French'), ('German', 'German'), ('Portuguese', 'Portuguese'), ('Spanish', 'Spanish')], default=' ', max_length=30, verbose_name='Language in which the data is written')),
                ('last_accessed', models.DateField(auto_now=True, null=True, verbose_name='Last known access')),
                ('last_modified', models.DateField(auto_now_add=True, verbose_name='Last record update')),
                ('last_refreshed', models.DateField(default=' ', verbose_name='Last known refresh date')),
                ('license_type', models.CharField(default=' ', max_length=30, verbose_name='License type (e.g. Open Data Commons)')),
                ('pii', models.BooleanField(default=False, verbose_name='Does source contain personally-identifiable information?')),
                ('records', models.BigIntegerField(blank=True, default=' ', null=True, verbose_name='Last known record count')),
                ('json_schema', models.TextField(blank=True, default=' ', max_length=30, null=True, verbose_name='RegEx expression used with access method')),
                ('schema_type', models.CharField(choices=[('None', 'None'), ('Column Headers', 'Column Headers'), ('AVRO', 'AVRO'), ('HXL', 'HXL'), ('JSON-LD', 'JSON-LD'), ('RDF', 'RDF'), ('XML', 'XML')], default=None, max_length=30, verbose_name='Schema type used to describe data source attributes')),
                ('size', models.BigIntegerField(blank=True, default=' ', null=True, verbose_name='Last known size (MB)')),
                ('system_of_record', models.BooleanField(default=False, max_length=30, verbose_name='Is this is a primary resource? (i.e. not a replica or extract)')),
                ('uri_access', models.URLField(default=' ', max_length=100, verbose_name='Access URI for data')),
                ('uri_documenation', models.URLField(blank=True, default=' ', max_length=100, null=True, verbose_name='Link to API documentation')),
                ('uri_endpoint', models.URLField(blank=True, default=' ', max_length=100, null=True, verbose_name='Access URI for endpoint API')),
                ('uri_schema', models.URLField(blank=True, default=' ', max_length=100, null=True, verbose_name='Access URI for schema (supply if schema_type is not "None")')),
                ('title', models.CharField(default=' ', max_length=255, verbose_name='Descriptive title (provided by maintainer)')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visible in view service')),
            ],
        ),
    ]
