# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 12:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisdatasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=30, verbose_name='Last Name')),
                ('middleName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name')),
                ('firstName', models.CharField(max_length=30, verbose_name='First Name')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=' ', max_length=30, verbose_name='Character encoding (e.g. UTF-8)')),
                ('phone_number', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('county', models.CharField(choices=[('BOMI', 'BOMI'), ('BONG', 'BONG'), ('GBARPOLU', 'GBARPOLU'), ('GRAND BASSA', 'GRAND BASSA'), ('GRAND GEDEH', 'GRAND GEDEH'), ('GRAND KRU', 'GRAND KRU'), ('GRAND CAPE MOUNT', 'GRAND CAPE MOUNT'), ('MARGIBI', 'MARGIBI'), ('MARYLAND', 'MARYLAND'), ('MONTSERRADO', 'MONTSERRADO'), ('NIMBA', 'NIMBA'), ('LOFA', 'LOFA'), ('RIVERCESS', 'RIVERCESS'), ('RIVERGEE', 'RIVERGEE'), ('SINOE', 'SINOE')], default=None, max_length=30, verbose_name='County')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('dateOfBirth', models.DateField(max_length=30, verbose_name='Date of Birth')),
                ('placeOfBirth', models.CharField(max_length=255, verbose_name='Place of Birth')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('emergency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone (Emergency Contact)')),
                ('previous_school', models.CharField(max_length=255, verbose_name='Previous School Attended')),
                ('transcript', models.FileField(blank=True, max_length=255, null=True, upload_to=b'', verbose_name='Transcript')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ELEMENTARY', 'ELEMENTARY'), ('JUNIOR HIGH', 'JUNIOR HIGH'), ('SENIOR HIGH', 'SENIOR HIGH')], default=None, max_length=255, verbose_name='Level')),
                ('grade', models.CharField(choices=[('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default=None, max_length=255, verbose_name='Class')),
                ('student_photo', models.FileField(max_length=255, upload_to=b'', verbose_name='Picture')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Sisdatasource',
        ),
    ]
