# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisdatasources', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisdatasources.Teacher'),
        ),
    ]
