# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisdatasources', '0002_auto_20161108_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Modified'),
        ),
    ]
